---
- hosts: all
  gather_facts: false
  tasks:
    - name: Deploy Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        manifest: "deployment.yml"
        kubeconfig: "/root/.kube/config"

     - name: Deploy Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        manifest: "service.yml"
        kubeconfig: "/root/.kube/config"
