---
- name: Deploy to Kubernetes
  hosts: localhost
  vars:
    kubeconfig: k8sconfigpwd
    configs:
      - deployment.yml
      - service.yml
  tasks:
    - name: Apply Kubernetes configurations
      command: kubectl apply -f {{ item }} --kubeconfig={{ kubeconfig }}
      loop: "{{ configs }}"
