---
- name: Deploy Kubernetes deployment
  hosts: ansiblegroup
  gather_facts: false
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  tasks:
    - name: Deploy Kubernetes resources
      kubernetes.core.k8s:
        kubeconfig: "/root/.kube/config"
        state: present
        resource_definition: "{{ lookup('file', 'deployment.yml') }}"
