---
- name: Deploying Application to Kubernetes
  hosts: all
  gather_facts: false
  vars:
    kubeconfig_file: ~/.kube/config
    namespace_name: app-ns
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_file }}"
        name: "{{ namespace_name }}"
        api_version: v1
        kind: Namespace
        state: present

    - name: Create Deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_file }}"
        state: present
        src: deployment.yml
        namespace: "{{ namespace_name }}"

    - name: Expose application on NodePort
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_file }}"
        state: present
        src: service.yml
        namespace: "{{ namespace_name }}"
