---
- hosts: ansiblegroup
  gather_facts: no  # Disable fact gathering for this task

  tasks:
    - name: Deploy Kubernetes deployment
      kubernetes.core.k8s:
        kubeconfig: "/root/.kube/config"  
        configs: "/var/lib/jenkins/workspace/medicure/deployment.yml" 
        state: present
