---
- name: Deploy Kubernetes resources
  hosts: all
  gather_facts: false
  tasks:
    - name: Deploy Kubernetes Deployment
      kubernetes.core.k8s:
        kubeconfig: "/root/.kube/config"  # Path to your kubeconfig file
        state: present
        resource_definition: "{{ lookup('file', 'deployment.yml') }}"  # Refers to your deployment file

    - name: Deploy Kubernetes Deployment
      kubernetes.core.k8s:
        kubeconfig: "/root/.kube/config"  # Path to your kubeconfig file
        state: present
        resource_definition: "{{ lookup('file', 'service.yml') }}"  # Refers to your deployment file
