---
- hosts: all
  gather_facts: no  # Disable fact gathering for this task

  tasks:
    - name: Deploy Kubernetes deployment
      kubernetes.core.k8s:
        kubeconfig: "/root/.kube/config"  # Path to your kubeconfig file
        namespace: "{{ namespace }}"          # Kubernetes namespace
        manifest: "deployment.yml"  # Path to your deployment YAML file
        user: "devops" # User to impersonate
        state: present
