---
- name: Deploy Kubernetes resources
  hosts: all
  gather_facts: false
  tasks:
    - name: Deploy Kubernetes Deployment
      kubernetes.core.k8s:
        kubeconfig: "/root/.kube/config"  # Adjust the path based on your setup
        state: present
        resource_definition: "{{ lookup('file', 'deployment.yml') }}"  # References your deployment.yml file

     - name: Deploy Kubernetes Deployment
        kubernetes.core.k8s:
          kubeconfig: "/root/.kube/config"  # Adjust the path based on your setup
          state: present
          resource_definition: "{{ lookup('file', 'service.yml') }}"  # References your deployment.yml file
