---
- name: Deploy Kubernetes resources
  hosts: all
  gather_facts: false
  tasks:
    - name: Deploy Deployment YAML
      kubernetes.core.k8s:
        kubeconfig: "/root/.kube/config"
        state: present
        resource_definition: "{{ lookup('file', 'deployment.yml') }}"

    - name: Deploy Service YAML
      kubernetes.core.k8s:
        kubeconfig: "/root/.kube/config"
        state: present
        resource_definition: "{{ lookup('file', 'service.yml') }}"
