kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydep
spec:
  replicas: 1
  selector:
    matchLabels:
      name: deployment
  template:
    metadata:
      name: template1
      labels:
        name: deployment
    spec:
      containers:
       - name: c01
         image: vigneshwar1908/medicure_healthcare:v1
